### ISSUE TITLE
Timestamp Format Issue

### ISSUE THREAD

**Issue by ChrisP1118** [lTimeless/Serilog.Sinks.AspNetCore.SignalR#2]
The string used to format the date portion of timestamps is using "mm" (for minutes) instead of "MM" (for months). Right now, for instance, I'm getting a timestamp of "29.49.2020 22:49:18.860", rather than "29.29.2020 22:49:18.860".

https://github.com/lTimeless/Serilog.Sinks.AspNetCore.SignalR/blob/0b76e3e8b1e94d3a3a2e7da1e2da3756061863a0/SignalRSink.cs#L110

**Comment by maxstue** [comment]
@ChrisP1118  Thank you for helping it is now fixed :)
