### ISSUE TITLE
application hangs when sending to clients

### ISSUE THREAD

**Issue by alexschultz** [lTimeless/Serilog.Sinks.AspNetCore.SignalR#3]
https://github.com/lTimeless/Serilog.Sinks.AspNetCore.SignalR/blob/0b76e3e8b1e94d3a3a2e7da1e2da3756061863a0/SignalRSink.cs#L65

I ran into an issue where the application would hang on the second call to this method. The issue seemed to be caused due to the fact that it's trying to set the hub context even when it's not null. I recommend wrapping this call in a null check to ensure you're not trying to set the field more than once. After I did this it started working.

**Comment by maxstue** [comment]
@alexschultz Thank you for helping it is now fixed :)
