### ISSUE TITLE
Json configuration of the SignalR sink

### ISSUE THREAD

**Issue by harry-flw** [lTimeless/Serilog.Sinks.AspNetCore.SignalR#5]
Hello.

I have tried to use the SignalR sink.

I have the LogHub class and ILogHub interface. 

When I use it from code like .WriteTo.SignalRSink<LogHub, ILogHub> it works.

How can I set up my appsettings.json config to use SignalRSink<LogHub, ILogHub> ?

I have tried different variants without any success.

Could you please help me with this issue?

Thanks a lot!

**Comment by maxstue** [comment]
Hi, sorry for the late response, I didn't get notified about a new issue.  
What exactly do you want to write in the "appsettings.json" file?

Do you want to set it up like other Serilog settings ? 
If yes, I didn't implement anything like that and I only thought about a "code-first" approach.
